<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\iOS\" />
    <Folder Include="Models\Requests\iOS\" />
    <Folder Include="Models\Responses\iOS\" />
    <Folder Include="Queries\iOS\" />
    <Folder Include="Utils\Android\" />
    <Folder Include="Utils\iOS\" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="MediatR" Version="11.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
